title: "So-Called Christian"
description: "New Testament and church history cheat sheets"
theme: minima
header_pages: []
plugins:
  - jekyll-sitemap
url: "https://socalledchristian.com"
permalink: /:basename
defaults:
  - scope:
      path: "assets/pdfs/**/*.pdf"
    values:
      sitemap: false
